title: jedrzejczyk.dev
description: >-
  Dariusz Jędrzejczyk notes on software engineering, coding and programming.
baseurl: ""
url: "https://jedrzejczyk.dev"

# Build settings
theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed

# theme-specific settings
header_pages:
  - index.md
  - talks.md
  - about.md

style: dark
listen_for_clients_preferred_style: true

footer: 'find me on <a href="https://github.com/chemicL">github</a> or <a href="https://twitter.com/chemicL">twitter</a>.'

kramdown:
  hard_wrap: false
